version: '2'
services:
  statsd:
    image: hopsoft/graphite-statsd
    ports:
      - "80:80"
      - "2003:2003"
      - "8125:8125/udp"
  spider:
    image: dirbot:spider
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt/scrapy
    links:
      - statsd
    ports:
      - "8125:8125/udp"

